title: null
name: Substrate Web3 DNS Tutorial
use_logo: true
logo: https://pact.online/dist/img/starlog_new.png

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

exclude: ["README.md"]
