title: Substrate Web3 DNS Tutorial
theme: minima

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

# exclude: ["README.md"]
